### ISSUE TITLE
Fix flake8 issues

### ISSUE THREAD

**Issue by chimosky** [44yu5h/rpi_control_center#1]
Flake8 currently shows about 216 issues, please fix them.

**Comment by chimosky** [comment]
I haven't been able to review any of the changes you've made with regards to the issues I opened as they're all separate and not supposed to be one giant commit, please don't make them one giant commit next time.

**Comment by 44yu5h** [comment]
It was a raw version which I wrote on Rpi. I had to furnish it a bit :)  Anyway, it won't happen again. Not in a giant commit.
Thanks
