### ISSUE TITLE
Radiobutton cb

### ISSUE THREAD

**Issue by chimosky** [44yu5h/rpi_control_center#2]
What are the odds that more checks would be added in the future?
```python3
def on_radiobutton_toggle(self, _b, name):
        if name == 'gpio':
            self.set_canvas(rp_gpio.gui())
        elif name == 'i2c':
            self.set_canvas(rp_i2c.gui())
        elif name == 'cam':
            self.set_canvas(rp_camera.gui())
        elif name == 'settings':
            self.set_canvas(rp_settings.gui())
        elif name == 'audio':
            self.set_canvas(rp_audio.gui())
        elif name == 'spi':
            self.set_canvas(rp_spi.gui())
```

Also, we use the convention `function_name_cb` because it's a callback.

**Comment by 44yu5h** [comment]
Fixed. Thanks!


``` python3
def radiobutton_cb(self, _b, name):
        options = {
            'gpio': rp_gpio.gui,
            'i2c': rp_i2c.gui,
            'cam': rp_camera.gui,
            'settings': rp_settings.gui,
            'audio': rp_audio.gui,
            'spi': rp_spi.gui
        }
```


> What are the odds that more checks would be added in the future?

These are sufficiently enough but we can have open minds.

**Comment by chimosky** [comment]
> These are sufficiently enough but we can have open minds.

If there's a tendency that this will change, then we need to do better.

I'll open a PR, if I figure something better.

In the future, it'll be great if you opened a PR instead of pushing directly, so we can agree on your changes before they're merged.
