### ISSUE TITLE
License

### ISSUE THREAD

**Issue by chimosky** [44yu5h/rpi_control_center#3]
Only `setup.py` contains an excerpt from the license, and it has someone else's name.

You should put the excerpts where necessary, and correct the name.

**Comment by 44yu5h** [comment]
Removed the previous license in [`setup.py`](https://github.com/44yu5h/rpi_control_center/blob/master/setup.py).

I built this activity on top of the hello-world example. I believe the previous licenses don't apply anymore.
Correct me if I'm wrong, I don't know much about licenses.

Thanks!

**Comment by chimosky** [comment]
You're the author, you decide what license you want to use, we ask that they're [OSI approved](https://opensource.org/licenses).

PS: you can learn more about licenses if you want to.
