### ISSUE TITLE
Streamline use of Gdk.RGBA

### ISSUE THREAD

**Issue by chimosky** [44yu5h/rpi_control_center#4]
You've used `Gdk.RGBA` in lots of places, it'll be good to have one function that does what needs to be done and imported where needed, we've done it like [this](https://github.com/sugarlabs/swiftfeet-activity/blob/488d346cf40009055d4f648a1c15e2faba252a14/activity.py#L61) in the past.

Is the use of `print` [here](https://github.com/44yu5h/rpi_control_center/blob/master/rp_tests/rp_gpio.py#L127) meant for debugging?

**Comment by 44yu5h** [comment]
Removed the redundancy (condensed to [one place](https://github.com/44yu5h/rpi_control_center/blob/master/activity.py#L74))

Thanks!

**Comment by chimosky** [comment]
Also, some changes shouldn't be squeezed in with others like flake8 changes.
